// Automatycznie wygenerowane dane - nie edytuj ręcznie!
const USD_TO_PLN = 3.765952;
const stocksData = {
  "NVDA": {
    "symbol": "NVDA",
    "fullname": "NVIDIA Corporation",
    "logo": "🟢",
    "logoBg": "#76B900",
    "desc": "Lider infrastruktury AI. Architektura Blackwell napędza potężny popyt od dostawców chmury (hyperscalerów). Wskazuje na punkt zwrotny agentów sztucznej inteligencji (agentic AI) jako nowy cykl wzrostowy.",
    "why": "Nvidia jest liderem infrastruktury AI. Przychody z data center wzrosły o 92% r/r w Q1 FY2027, a CEO Jensen Huang mówi o 'agentic AI inflection point' jako nowym cyklu wzrostowym. Architektura Blackwell napędza popyt od hyperscalerów, dostawców chmury AI i klientów suwerennych. Jedynym ryzykiem są ograniczenia eksportowe do Chin.",
    "growth2026": "61.0%",
    "rating": "Strong Buy",
    "potential": "+14.0%",
    "pe": "30.7",
    "divYield": "0.50%",
    "marketCap": "$4.85T USD",
    "oneYearReturn": "+30.70%",
    "returnNumeric": 30.69568495169987,
    "fallbackPrice": 200.09,
    "sector": "Półprzewodniki i AI"
  },
  "LLY": {
    "symbol": "LLY",
    "fullname": "Eli Lilly and Company",
    "logo": "🧬",
    "logoBg": "#E00000",
    "desc": "Farmaceutyczny gigant napędzany rewolucyjnym popytem na leki odchudzające i przeciw otyłości (Mounjaro, Zepbound), wspierany trendami longevity i starzejącego się społeczeństwa.",
    "why": "Globalny boom na leki GLP-1 (Mounjaro, Zepbound) napędza rekordowy wzrost. W Q1 2026 przychody z leków na cukrzycę i otyłość wzrosły o 125% (Mounjaro) i 80% (Zepbound). Starzejąca się populacja i trend longevity tworzą długoterminowy popyt. To spółka o najwyższym wzroście przychodów w sektorze zdrowia.",
    "growth2026": "30.4%",
    "rating": "Buy",
    "potential": "+18.0%",
    "pe": "42.5",
    "divYield": "0.58%",
    "marketCap": "$1.07T USD",
    "oneYearReturn": "+55.68%",
    "returnNumeric": 55.67919005311711,
    "fallbackPrice": 1199.43,
    "sector": "Farmacja i Zdrowie"
  },
  "TSM": {
    "symbol": "TSM",
    "fullname": "Taiwan Semiconductor Manufacturing Company Limited",
    "logo": "🔌",
    "logoBg": "#005EB8",
    "desc": "Największa na świecie niezależna odlewnia półprzewodników. Produkuje najbardziej zaawansowane chipy na świecie dla gigantów takich jak Nvidia, Apple czy AMD, stanowiąc kręgosłup sektora technologicznego.",
    "why": "Kluczowy element globalnego łańcucha dostaw AI. Wzrost zapotrzebowania na układy Blackwell od Nvidii oraz procesory Apple bezpośrednio przekłada się na wyniki spółki. W 2026 roku TSMC umacnia swoją pozycję monopolisty w segmencie chipów 2nm i 3nm.",
    "growth2026": "28.0%",
    "rating": "Buy",
    "potential": "+15.0%",
    "pe": "41.5",
    "divYield": "0.80%",
    "marketCap": "$2.48T USD",
    "oneYearReturn": "+114.91%",
    "returnNumeric": 114.9063786858766,
    "fallbackPrice": 477.57,
    "sector": "Półprzewodniki"
  },
  "GOOG": {
    "symbol": "GOOG",
    "fullname": "Alphabet Inc.",
    "logo": "🔍",
    "logoBg": "#4285F4",
    "desc": "Lider wyszukiwania internetowego rozwijający chmurę Google Cloud (wzrost o 63%) oraz płatne subskrypcje modeli Gemini. Najtańszy wycenowo gigant z technologicznego TOP 5.",
    "why": "Alphabet jest jednym z najsilniejszych performerów w 2026 roku — wskoczył z 4. na 2. miejsce pod względem kapitalizacji. Google Cloud rośnie o 63%, a backlog chmury prawie się podwoił do ponad $460 mld. Model Gemini ma już 350 mln płatnych subskrypcji. Przy P/E = 23 jest najtańszym gigantem tech z najwyższym wzrostem.",
    "growth2026": "20.0%",
    "rating": "Buy",
    "potential": "+15.0%",
    "pe": "27.0",
    "divYield": "0.25%",
    "marketCap": "$4.31T USD",
    "oneYearReturn": "+100.29%",
    "returnNumeric": 100.29333201625712,
    "fallbackPrice": 353.33,
    "sector": "Wyszukiwarki i Chmura AI"
  },
  "AMZN": {
    "symbol": "AMZN",
    "fullname": "Amazon.com, Inc.",
    "logo": "📦",
    "logoBg": "#FF9900",
    "desc": "Dominator rynku e-commerce i chmury AWS, przeżywający rewolucję dzięki automatyzacji logistyki i rosnącym przychodom reklamowym. Uznawany za bezpieczną przystań o stabilnym wzroście.",
    "why": "AWS odnotowuje najszybszy wzrost sprzedaży od ponad 3 lat, a Amazon jest nazywany 'catch-up trade' — spółką, której momentum dopiero zaczyna być wyceniane. Reklama rośnie o 18%, a Prime o 9% r/r. Automatyzacja logistyki poprawia marże e-commerce. To najbezpieczniejszy wybór z piątki — solidny wzrost przy dużej kapitalizacji.",
    "growth2026": "15.0%",
    "rating": "Buy",
    "potential": "+12.0%",
    "pe": "31.7",
    "divYield": "Brak",
    "marketCap": "$2.56T USD",
    "oneYearReturn": "+8.11%",
    "returnNumeric": 8.110309842832262,
    "fallbackPrice": 238.34,
    "sector": "E-commerce i Chmura AWS"
  }
};
